name: Build Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/docs/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/docs/**'

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('pnpm-lock.json') }}

      - name: Install dependencies
        run: pnpm --filter docs install

      - name: Lint
        run: pnpm --filter docs lint

      - name: Build
        run: pnpm --filter docs build
